"""Initial migration for Excel upload module

Revision ID: 5e4e6034db2f
Revises: 
Create Date: 2025-12-11 11:58:27.737066

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e4e6034db2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_excel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='文件名'),
    sa.Column('original_name', sa.String(length=255), nullable=True, comment='原始文件名'),
    sa.Column('href', sa.String(length=255), nullable=True, comment='文件路径'),
    sa.Column('mime', sa.String(length=255), nullable=True, comment='文件类型'),
    sa.Column('size', sa.Integer(), nullable=True, comment='文件大小'),
    sa.Column('upload_time', sa.DateTime(), nullable=True, comment='上传时间'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='文件描述'),
    sa.Column('status', sa.Integer(), nullable=True, comment='状态：0-禁用，1-启用'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_apscheduler_jobs_next_run_time')

    op.drop_table('apscheduler_jobs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_apscheduler_jobs_next_run_time', ['next_run_time'], unique=False)

    op.drop_table('admin_excel')
    # ### end Alembic commands ###
